//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloridaBikeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        public long ID { get; set; }
        public string documento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public long telefono { get; set; }
        public string direccion { get; set; }
    
        public virtual Bicicleta Bicicleta { get; set; }
    }
}
